name: KU Routine Sync

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Restore caches
        uses: actions/cache@v3
        with:
          path: |
            token.pkl
            last_hash.txt
          key: routine-cache

      - name: Run KU Routine Sync
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python main.py

      - name: Save caches
        uses: actions/cache@v3
        with:
          path: |
            token.pkl
            last_hash.txt
          key: routine-cache
