name: KU Routine Sync

on:
  schedule:
    - cron: '*/30 * * * *'  # every 30 minutes
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Decode token.pkl from secret
        run: echo "${{ secrets.GOOGLE_TOKEN_PKL_B64 }}" | base64 -d > token.pkl

      - name: Restore caches
        uses: actions/cache@v3
        with:
          path: |
            last_hash.txt
          key: routine-cache

      - name: Run KU Routine Sync
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python main.py

      - name: Save caches
        uses: actions/cache@v3
        with:
          path: |
            last_hash.txt
          key: routine-cache